### ISSUE TITLE
AutoComplete popup does not show under Windows 10's Terminal

### ISSUE THREAD

**Issue by gabest11** [FarGroup/FarManager#262] opened 2020-08-03 19:04 UTC
I compiled Far Manager and see what's different in Terminal. In `EditControl::AutoCompleteProc` `console.GetNumberOfInputEvents` sets `EventsCount` to 1 and skips the whole function because of it. If I just change the value to 0 after a break point, it continues normally and I can see the popup.

**Comment by gabest11** [comment] 2020-08-03 20:13
Not sure, but I think it's because the queue already contains the matching keyup code for the last letter. This does not happen with cmd.exe.

**Comment by gabest11** [comment] 2020-08-03 20:36
This quick workaround seem to work. 

In `EditControl::AutoCompleteProc`, just after `console.GetNumberOfInputEvents`.

```
if(EventsCount == 1)
{
	INPUT_RECORD rec;
	if(console.PeekOneInput(rec) && rec.EventType == KEY_EVENT && !rec.Event.KeyEvent.bKeyDown)
		EventsCount = 0;
}
```

**Comment by DHowett** [comment] 2020-08-03 20:43
Thanks for finding the root cause!

Applications should not take a dependency on any particular input event ordering. Over different link types, or with different types of keyboard, there is no guarantee that the Key Up event doesn't come at the same time as the key down event. Due to event coalescing and aggregation, they could come at any point so long as they are ordered correctly.

**Comment by alabuzhev** [comment] 2020-08-03 20:43
We use [GetNumberOfConsoleInputEvents](https://docs.microsoft.com/en-us/windows/console/getnumberofconsoleinputevents) there for a reason: some people use <kbd>console window menu</kbd> - <kbd>edit</kbd> - <kbd>paste</kbd> to paste a text into the window (or some third-party software which essentially does the same). In this case the input comes to us a a series on individual keystrokes and we don't want to trigger the completion after each of them, because it makes the input slow and blinky.
This logic has been there since [2012](https://github.com/FarGroup/FarManager/commit/d652c25ccbf906423e58a83fc386bb045db7c4ca#diff-b530cadadff5e3212e1bfb2a53033b1f) and haven't caused any issues so far.

If GetNumberOfConsoleInputEvents API reports 1 under this new terminal and 0 under the default console host after receiving the identical keyboard input - it's (supposedly) a bug in the terminal.

**Comment by gabest11** [comment] 2020-08-03 20:54
Yes, I noticed there can be multiple keys in the queue, just holding a single key, or backspace. It makes sense to only show the auto complete menu if the queue is empty. However I don't agree with Terminal being faulty. The key down and key up commands may be placed in the input queue of Far Manager simultaneously. I'm trying to compile Terminal, but it's a PITA store app.

**Comment by gabest11** [comment] 2020-08-03 20:58
You may ask why I even bother using Far inside Terminal. The new console implementation has issues with DPI and resizing, the legacy console is a global setting and it has problems with Python, so...

**Comment by alabuzhev** [comment] 2020-08-03 21:00
@DHowett , I think this might be the cause:

Please take this tool - [readkey.zip](https://github.com/FarGroup/FarManager/files/5018508/readkey.zip) - and do the following under both conhost and terminal:
- Press any key, e.g. <kbd>Space</kbd>
- Hold it for a while
- Release it
- Compare the output.

Conhost:
```
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000020 (casac - ecNs)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000020 (casac - ecNs)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000020 (casac - ecNs)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000020 (casac - ecNs)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000020 (casac - ecNs)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000020 (casac - ecNs)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000020 (casac - ecNs)
KEY_EVENT_RECORD: Up, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000020 (casac - ecNs)
```

Terminal:
```
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Up, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Up, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Up, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Up, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Up, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Up, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Down, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
KEY_EVENT_RECORD: Up, Count=1, Vk=VK_SPACE [32/0x20], Scan=57, uChar=[U=' '(0x0020) A=' '(0x20)], Control=0x00000000 (casac - ecns)
```

I.e. terminal reports paired false "Up" events even though the key stays down.

**Comment by gabest11** [comment] 2020-08-03 21:03
Ouch. That's not nice.

**Comment by gabest11** [comment] 2020-08-03 21:04
Although, what happens if you just press it once? Then the your log looks the same and there is still no auto complete.

**Comment by alabuzhev** [comment] 2020-08-03 21:12
> Although, what happens if you just press it once? Then your log looks the same and there is still no auto complete.

If terminal sends the Up event instantaneously after the Down event, and not when I release the key as it should, it's not surprising that the Up is already in the input queue while we're still processing the Down event.

In any case, the current terminal behaviour regarding Up and Down event is:
- illogical
- a breaking change.

**Comment by gabest11** [comment] 2020-08-03 21:15
Ok, it does lie about the time of release. But where does this affect the input processing of Far? It relies on a race condition, where it can remove the down event before the sender can put the up event into the queue.

**Comment by gabest11** [comment] 2020-08-03 21:28
Just found this gem in Terminal's code:

```
    // Unfortunately, the UI doesn't give us both a character down and a
    // character up event, only a character received event. So fake sending both
    // to the terminal input translator. Unless it's in win32-input-mode, it'll
    // ignore the keyup.
    KeyEvent keyDown{ true, 1, vkey, scanCode, ch, states.Value() };
    KeyEvent keyUp{ false, 1, vkey, scanCode, ch, states.Value() };
    const auto handledDown = _terminalInput->HandleKey(&keyDown);
    const auto handledUp = _terminalInput->HandleKey(&keyUp);
    return handledDown || handledUp;

```

**Comment by DHowett** [comment] 2020-08-03 21:29
You're not wrong about it being a breaking change, but it's a breaking change for clients who should be robust enough to handle it.

The core issue is that there is not a broad standard in use that allows for a VT encoding of make/break sequences. There's no widely-compatible mechanism for communicating a key's _press_ and _release_ separately over SSH. The few specifications there are (DECKPM, DECSMKR, DECPCTERM) are not offered by any terminal emulator, and there is a handful of homegrown implementations (libtickit, kitty's make/break extension).

Given that the entire rest of the world settled on key _press_ being the event of repute and chose to discard key _release_, it's not illogical at all.

**Comment by DHowett** [comment] 2020-08-03 21:32
I'm moving this part of the discussion over to #3910, and will mark my comment off-topic (if I can.)

**Comment by alabuzhev** [comment] 2020-08-03 21:33
Indeed, the completion menu manages to pop up and check the input queue status *before* you release the key (computers are way faster than humans).
I wouldn't call that a race condition - it's a deliberate filtering of events-that-are-coming-way-too-fast, and it's not its fault that the up event is coming instantaneously now.

Your workaround above seems logical though. Given that the issue is unlikely to be fixed in terminal, I'll apply it.

**Comment by gabest11** [comment] 2020-08-03 21:35
I'm just a long time Far user, who wants to continue using it in the future, don't know much about terminal emulation. Hopefully there will be a good solution to this, because auto complete is one of the essential features, remembering all the commands I ever used is impossible.

**Comment by alabuzhev** [comment] 2020-08-03 21:56
Workaround added in 85b5859 / 5648.

**Closed by alabuzhev** 2020-08-03 21:56 UTC
