### ISSUE TITLE
Network plugin crash on directory change

### ISSUE THREAD

**Issue by LuckyTil** [FarGroup/FarManager#631] opened 2023-02-22 17:13 UTC
### Far Manager version

3.0.6101.0

### OS version

10.0.19045.2604

### Steps to reproduce

Crash report
[Far_20230222_170751075_62568.zip](https://github.com/FarGroup/FarManager/files/10806533/Far_20230222_170751075_62568.zip)

### Actual behavior

Crash report

**Comment by alabuzhev** [comment] 2023-02-22 19:28
@LuckyTil Looks like it happened when you were using the network browser plugin and tried to change the directory. Unfortunately that is not enough to reproduce the issue.
Are any specific steps needed? Did it happen once / more than once? What exactly you were doing?

I see a few third party plugins in the list (DiskMenu, MsiUpdate, PortaDev, RCl2, Renewal), maybe try without them if nothing else helps.

**Comment by LuckyTil** [comment] 2023-02-22 19:43
Я столкнулся с этим 2-й раз за год.
Проявилось при смене текущего сетевого пути на другой сетевой путь через историю папок (Alt-F12).

**Comment by alabuzhev** [comment] 2023-02-22 21:04
Found it I think. Should be fixed in Network build 107.

Please reopen if it crashes again.

**Closed by alabuzhev** 2023-02-22 21:04 UTC
Labels: bug
