### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by LuckyTil** [FarGroup/FarManager#777] opened 2024-01-20 20:28 UTC
### Far Manager version

3.0.6226.0

### OS version

10.0.22631.3007

### Steps to reproduce

1. Open attachment
2. Analyze content
[Far_20240120_202126566_8640.7z.zip](https://github.com/FarGroup/FarManager/files/13999155/Far_20240120_202126566_8640.7z.zip)

### Actual behavior

See attachment

**Comment by LuckyTil** [comment] 2024-01-20 20:30
Another attachments
[Far_20230624_211615009_41600.7z.zip](https://github.com/FarGroup/FarManager/files/13999157/Far_20230624_211615009_41600.7z.zip)
[Far_20230627_144733202_27788.7z.zip](https://github.com/FarGroup/FarManager/files/13999158/Far_20230627_144733202_27788.7z.zip)
[Far_20230903_182747372_1616.7z.zip](https://github.com/FarGroup/FarManager/files/13999160/Far_20230903_182747372_1616.7z.zip)

**Comment by HamRusTal** [comment] 2024-01-20 20:49
This Issue misses all key elements of a good bug report: a specific concise yet meaningful title, clear Steps to Reproduce, unambiguous Expected and Actual behavior. These should not be buried in numerous attached archive without a very solid reason (and the reason, if any, has to be explained).
I suggest that this issue is either reworked fundamentally or rejected right away.

**Comment by alabuzhev** [comment] 2024-01-20 22:33
Meh. Sometimes a memory dump is way better than any user stories.

I see that:
- the user pressed enter on a png file
- far read some data from it and started demonstrating it to plugins
- eventually it reached netbox, loaded it, asked it to populate the PluginInfo structure
- accessed the data in the structure and crashed, because it was rubbish.

Looking at the netbox code, the data is heap-allocated and should live at least till the next call of GetPluginInfo, so it is unlikely its fault.
Far doesn't call GetPluginInfo twice during this operation, so it is unlikely its fault either.
The only way to prematurely invalidate the data is another GetPluginInfo call by another plugin from another thread.

So... as usual: remove 3rdparty plugins and see how it goes.

P.S. I see Renewal in the plugins list and also a working thread spawned by it.
As far as I remember, it does call some APIs to get plugins versions from a background thread and it did cause similar issues in the past, so I'd start from it. If that's the case, turning off automatic checks in its settings and updating manually might help.

**Comment by MKadaner** [comment] 2024-01-20 23:24
> Meh. Sometimes a memory dump is way better than any user stories.

I tend to agree with R Kh that this bug report could be improved. Something on the lines of "Crash" instead of "Bug report" in the issue title would not hurt. "I pressed enter on a png file," in the "Steps to reproduce" does not require huge effort either.

Even if this extra information would not help with analysis, somebody else with a similar issue might have worked out the solution on his own.

**Comment by LuckyTil** [comment] 2024-01-21 07:46
> This Issue lacks all key elements of a good bug report: a specific concise yet meaningful title, clear Steps to Reproduce, unambiguous Expected and Actual behavior. These should not be buried in numerous attached archives without a very solid reason (and the reason, if any, has to be explained).
> I suggest that this issue is either reworked fundamentally or rejected right away.

No. This was issue created in strict accordance with the instructions:
"Please send bug_report.txt and far.mdmp to the developers:

  https://github.com/FarGroup/FarManager/issues
..."

**Comment by MKadaner** [comment] 2024-01-21 20:53
> This was issue created in strict accordance with the instructions:
> "Please send bug_report.txt and far.mdmp to the developers:

Not exactly. The "New issue" page has the following message at the top:

> Please make sure to [search for existing issues](https://github.com/FarGroup/FarManager/issues), [check the FAQ](https://forum.farmanager.com/viewtopic.php?t=5207) and [reporting guidelines](https://farmanager.com/problems.php?l=en) before filing a new one.

The last link is the most relevant in this case.

**Comment by LuckyTil** [comment] 2024-01-22 07:53
> Not exactly. The "New issue" page has the following message at the top:

Instructions were obtained from the exception message issued by Far Manager.

**Comment by alabuzhev** [comment] 2024-01-22 11:39
> Instructions were obtained from the exception message issued by Far Manager.

Fair enough. [I've updated it](https://github.com/FarGroup/FarManager/commit/ee700d9f138105717313a4cdae5c22e1911000f2).

Anyway, back to the topic.
As I mentioned earlier, the issue is likely due to a thirdparty plugin and there is nothing for us to fix here, so closing for now.

**Closed by alabuzhev** 2024-01-22 11:39 UTC
Labels: bug

**Comment by HamRusTal** [comment] 2024-01-22 13:49
> [I've updated it](https://github.com/FarGroup/FarManager/commit/ee700d9f138105717313a4cdae5c22e1911000f2).

Wouldn't it be even better to remind a user to give the bug report a meaningful title mentioning “crash”?
Also, wouldn't it make sense to call the generated text file `crash_report.txt` rather than `bug_report.txt`?

**Comment by alabuzhev** [comment] 2024-01-22 14:04
@HamRusTal maybe. Please feel free to create a new issue and we can discuss it there.
