### ISSUE TITLE
AV in Netbox after notebook sleep

### ISSUE THREAD

**Issue by marinkaberg** [FarGroup/FarManager#849] opened 2024-06-11 01:30 UTC
### Far Manager version

3.0.6300.0

### OS version

10.0.22631.3593

### Other software

Netbox.

### Steps to reproduce

Connect to SFTP server with Netbox, open some file in Far editor by F4, then close the lid of the notebook to make it sleep. Go get some sleep yourself. Wake up, open the laptop lid: [bug_report.txt](https://github.com/user-attachments/files/15780793/bug_report.txt).

### Expected behavior

Not sure, but disconnection with SFTP server with red pop-up would be enough.

### Actual behavior

Far crashes.

**Comment by alabuzhev** [comment] 2024-06-11 21:48
Duplicate of #827

**Closed by alabuzhev** 2024-06-11 21:48 UTC
Labels: bug
